services:
  - type: web
    name: train-booking-api
    runtime: dotnet-core
    buildCommand: dotnet build
    startCommand: dotnet run
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    healthCheckPath: /api/booking
    plan: free 